authentication_homepage:
    path:     /login
    defaults: { _controller: AuthenticationBundle:Default:index }

authentication_logout:
    path:     /logout
    defaults: { _controller: AuthenticationBundle:Default:logout }
