# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        activedirectory:
            id: activedirectory_userprovider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            stateless: true   ## refreshUser not supported, so turn off session stuff
            
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path:         authentication_homepage
                check_path:         authentication_homepage
                username_parameter: login[username]
                password_parameter: login[password]
                
            ## Logout doesn't work because of stateless (doesn't call clearcookies)
            ## Also - doesn't seem to support "secure" cookies
            #logout: 
            #    target:             authentication_homepage
            #    invalidate_session: true
            #    delete_cookies:
            #        auth-cookie:      
            #            path:        /
            #            domain:      127.0.0.1
                
            guard:
                authenticators:
                    - authenticator_activedirectory
                
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
            simple_preauth: 
                # Turn cookie into a guard
                authenticator: authenticator_cookie_simple

    access_control:
        - { path: ^/login$,     role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/,           role: ROLE_USER, requires_channel: https }
